[theme]
primaryColor = "#00ff66"
backgroundColor = "#0f131d"
secondaryBackgroundColor = "#171b26"
textColor = "#dfe2f1"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false